### PR TITLE
Created using Colaboratory

### PR DESCRIPTION
**Pull request by VGGatGitHub**
This is ipython version of the run-length-encoding exercise from April 2nd. I did this within Google Colab but was not able to figure out how to place the file in the correct location of the repo. Hope we can discuss this at the next meetup.

### CODE REVIEW

**Comment by VGGatGitHub** [comment]
I think now the file is in the correct place :)

**Comment by bwestover** [comment]
This looks good, and will work to pass the tests if I move it into the `run_length_encoding.py` file. Thanks for the submission! :smile: 

You can edit the `run_length_encoding.py` file and copy/paste the code for the two functions from your Jupyter notebook, into that file. That is where the exercism tests expect to find it. I would be happy to accept these changes :+1:

**Comment by VGGatGitHub** [comment]
I just updated the run_length_encoding.py file using the ipynb and fixed the name of the ipynb file.

**Review by bwestover — APPROVED** [review]
This looks awesome. Thanks!

**Pull request merged**
